DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE FACTURAS CASCADE CONSTRAINTS;
DROP TABLE VEHICULOS CASCADE CONSTRAINTS;
DROP TABLE REPARACIONES CASCADE CONSTRAINTS;
DROP TABLE Intervienen CASCADE CONSTRAINTS;
DROP TABLE EMPLEADOS CASCADE CONSTRAINTS;
DROP TABLE Incluyen CASCADE CONSTRAINTS;
DROP TABLE RECAMBIOS CASCADE CONSTRAINTS;
DROP TABLE Realizan CASCADE CONSTRAINTS;
DROP TABLE ACTUACIONES CASCADE CONSTRAINTS;


CREATE TABLE CLIENTES (
CodCliente VARCHAR2(5) NOT NULL,
DNI VARCHAR2(10) NOT NULL,
Apellidos VARCHAR2(50),
Nombre VARCHAR2(25),
Direccion VARCHAR2(60),
Telefono VARCHAR2(9),
PRIMARY KEY (CodCliente)
);

CREATE TABLE FACTURAS (
IdFactura NUMBER(4) NOT NULL,
FechaFactura DATE NOT NULL,
CodCliente VARCHAR2(5) NOT NULL,
IdReparacion NUMBER,
PRIMARY KEY (IdFactura)
);

CREATE TABLE VEHICULOS (
Matricula VARCHAR2(8) NOT NULL,
Marca VARCHAR2(25),
Modelo VARCHAR2(50),
Color VARCHAR2(20),
FechaMatriculacion DATE,
CodCliente  VARCHAR2(5),
PRIMARY KEY(Matricula)
);

CREATE TABLE REPARACIONES (
IdReparacion NUMBER NOT NULL,
Matricula VARCHAR2(8) NOT NULL,
FechaEntrada DATE,
Km NUMBER(8,2),
Averia VARCHAR2(200),
FechaSalida DATE,
Reparado  NUMBER(1),
Observaciones VARCHAR2(250),
PRIMARY KEY(IdReparacion)
);

CREATE TABLE Intervienen (
CodEmpleado VARCHAR2(5),
IdReparacion NUMBER NOT NULL,
Horas NUMBER(4,2),
PRIMARY KEY(CodEmpleado, IdReparacion)
);

CREATE TABLE EMPLEADOS (
CodEmpleado VARCHAR2(5) NOT NULL,
DNI VARCHAR2(10) NOT NULL,
Nombre VARCHAR2(25),
Apellidos VARCHAR2(50),
Direccion VARCHAR2(60),
Telefono VARCHAR2(9),
CP VARCHAR2(5),
FechaAlta DATE,
Categoria VARCHAR2(50),
PRIMARY KEY(CodEmpleado)
);

CREATE TABLE Incluyen (
IdRecambio VARCHAR2(10) NOT NULL,
IdReparacion NUMBER NOT NULL,
Unidades NUMBER,
PRIMARY KEY (IdRecambio, IdReparacion)
);

CREATE TABLE RECAMBIOS (
IdRecambio VARCHAR2(10) NOT NULL,
Descripcion VARCHAR2(100),
UnidadBase VARCHAR2(50),
Stock NUMBER, 
PrecioReferencia NUMBER(6,2),
PRIMARY KEY(IdRecambio)
);

CREATE TABLE Realizan (
IdReparacion NUMBER NOT NULL,
Referencia VARCHAR2(10) NOT NULL,
Horas NUMBER(4,2),
PRIMARY KEY(IdReparacion, Referencia)
);

CREATE TABLE ACTUACIONES (
Referencia VARCHAR2(10) NOT NULL,
Descripcion VARCHAR2(100),
TiempoEstimado NUMBER(4,2),
Importe NUMBER(6,2),
PRIMARY KEY(Referencia)
);

ALTER TABLE FACTURAS
ADD CONSTRAINT FACT_FK_CodCli FOREIGN KEY(CodCliente) REFERENCES CLIENTES(CodCliente) 
ON DELETE CASCADE;

ALTER TABLE FACTURAS
ADD CONSTRAINT FACT_FK_IdRep FOREIGN KEY(IdReparacion) REFERENCES REPARACIONES(IdReparacion)
ON DELETE CASCADE;

ALTER TABLE VEHICULOS
ADD CONSTRAINT VEHIC_FK_CodCli FOREIGN KEY(CodCliente) REFERENCES CLIENTES(CodCliente)
ON DELETE CASCADE;

ALTER TABLE REPARACIONES
ADD CONSTRAINT REPAR_FK_CodRep FOREIGN KEY(Matricula) REFERENCES VEHICULOS(Matricula)
ON DELETE CASCADE;

ALTER TABLE Intervienen
ADD CONSTRAINT Inter_FK_CodEm FOREIGN KEY(CodEmpleado) REFERENCES EMPLEADOS(CodEmpleado)
ON DELETE CASCADE;

ALTER TABLE Intervienen
ADD CONSTRAINT Inter_FK_IdRep FOREIGN KEY(IdReparacion) REFERENCES REPARACIONES(IdReparacion)
ON DELETE CASCADE;

ALTER TABLE Incluyen
ADD CONSTRAINT Incluy_FK_IdRec FOREIGN KEY(IdRecambio) REFERENCES RECAMBIOS(IdRecambio)
ON DELETE CASCADE;

ALTER TABLE Incluyen
ADD CONSTRAINT Incluy_FK_IdRep FOREIGN KEY(IdReparacion) REFERENCES REPARACIONES(IdReparacion)
ON DELETE CASCADE;

ALTER TABLE Realizan
ADD CONSTRAINT Real_FK_IdRep FOREIGN KEY(IdReparacion) REFERENCES REPARACIONES(IdReparacion)
ON DELETE CASCADE;

ALTER TABLE Realizan
ADD CONSTRAINT Real_FK_Refer FOREIGN KEY(Referencia) REFERENCES ACTUACIONES(Referencia)
ON DELETE CASCADE;