
DROP TABLE ENTRADA_INVITACION CASCADE CONSTRAINTS;
DROP TABLE ENTRADA_COMPRADA CASCADE CONSTRAINTS;
DROP TABLE ENTRADA CASCADE CONSTRAINTS;
DROP TABLE SUPLENCIA CASCADE CONSTRAINTS;
DROP TABLE ACTUA_EN CASCADE CONSTRAINTS;
DROP TABLE PROYECCION CASCADE CONSTRAINTS;
DROP TABLE TECNICO CASCADE CONSTRAINTS;
DROP TABLE SALA CASCADE CONSTRAINTS;
DROP TABLE PELICULA CASCADE CONSTRAINTS;
DROP TABLE INTERPRETE CASCADE CONSTRAINTS;

-- Para eliminar el tablespace:
DROP TABLESPACE CINE INCLUDING CONTENTS AND DATAFILES;

